---
title: "Leaflet"
author: "StevenChang"
date: "11/20/2017"
output: html_document
---

```{r }
library(leaflet)
library(sp)
library(mapproj)
library(maps)
library(mapdata)
library(maptools)
library(htmlwidgets)
library(magrittr)
library(XML)
library(plyr)
library(rgdal)
library(WDI)
library(raster)
library(noncensus)
library(stringr)
library(tidyr)
library(tigris)
library(rgeos)
library(ggplot2)
library(scales)
data(zip_codes)
CancerRates <- read.csv('CancerCountyFIPS.csv')
CancerRatesB <- read.csv('CancerCountyFIPS_Breast.csv')
LandUse <- read.csv('LandUseDatasetREALLatlong.csv')
Hospitals <- read.csv('Hospitals.csv')
NuPowerPlant <- read.csv('energy-pop-exposure-nuclear-plants-locations_plants.csv')
USNuPowerPlant = subset(NuPowerPlant,Country == 'UNITED STATES OF AMERICA')

names(CancerRates) <- tolower(names(CancerRates))
colnames(CancerRates) <- c("location", "GEOID", "rate")
colnames(CancerRatesB) <- c("location", "GEOID", "rate")
colnames(LandUse) <- c("offset", "lat", "lng", "url", "name")

CancerRates$GEOID <- formatC(CancerRates$GEOID, width = 5, format = "d", flag = "0")
CancerRatesB$GEOID <- formatC(CancerRatesB$GEOID, width = 5, format = "d", flag = "0")

CancerRates <- separate(CancerRates, location, into = c("county", "state"), sep = ", ")
CancerRatesB <- separate(CancerRatesB, location, into = c("county", "state"), sep = ", ")

CancerRates[] <- lapply(CancerRates, function(x) gsub("\\s*\\([^\\)]+\\)", "", x))
CancerRatesB[] <- lapply(CancerRatesB, function(x) gsub("\\s*\\([^\\)]+\\)", "", x))
CancerRatesB[] <- lapply(CancerRatesB, function(x) gsub("\\#", "", x))

CancerRates$state <- state.abb[match(CancerRates$state,state.name)]
CancerRatesB$state <- state.abb[match(CancerRatesB$state,state.name)]

CancerRates$rate <- as.numeric(as.character(CancerRates$rate))
CancerRatesB$rate <- as.numeric(as.character(CancerRatesB$rate))
```

```{r}
#usmap
us.map <- tigris::counties(cb = TRUE, year = 2015)

us.map <- us.map[!us.map$STATEFP %in% c("02", "15", "72", "66", "78", "60", "69",
                                        "64", "68", "70", "74"),]
us.map <- us.map[!us.map$STATEFP %in% c("81", "84", "86", "87", "89", "71", "76",
                                        "95", "79"),]

#merge
cancermap <- merge(us.map, CancerRates, by=c("GEOID"))
cancermapB <- merge(us.map, CancerRatesB, by=c("GEOID"))

#popup
popup_nu<- paste0("<strong>Power Plant: </strong>", 
                    USNuPowerPlant$Plant, 
                    "<br><strong>Num of Reactor: </strong>", 
                    USNuPowerPlant$NumReactor)

popup_hos <- paste0("<strong>Hospital: </strong>", 
                    Hospitals$NAME, 
                    "<br><strong>Address: </strong>", 
                    Hospitals$ADDRESS)

popup_dat <- paste0("<strong>County: </strong>", 
                    cancermap$county, 
                    "<br><strong>Cancer Rate (Age Adjusted) Out of 100,000: </strong>", 
                    cancermap$rate)

popup_datB <- paste0("<strong>County: </strong>", 
                    cancermapB$county, 
                    "<br><strong>Cancer Rate (Age Adjusted) Out of 100,000: </strong>", 
                    cancermapB$rate)

popup_LU <- paste0("<strong>Use Name: </strong>", 
                   LandUse$name, 
                   "<br><strong>Link: </strong>", 
                   LandUse$url)
```

```{r}

pal <- colorQuantile("YlOrRd", NULL, n = 9)
gmap <- leaflet(data = cancermap) %>%
  # Base groups
  addTiles() %>%
  setView(lng = -105, lat = 40, zoom = 4) %>% 
  addPolygons(fillColor = ~pal(rate), 
              fillOpacity = 0.8, 
              color = "#BDBDC3", 
              weight = 1,
              popup = popup_dat,
              group="Cancer Rate/100,000 by Counties") %>%
  
  addPolygons(data=cancermapB,fillColor = ~pal(rate), 
              fillOpacity = 0.8, 
              color = "#BDBDC3", 
              weight = 1,
              popup = popup_datB,
              group="Breast Cancer Rate/100,000 by Counties") %>%
  
  # Overlay groups
  addMarkers(data=LandUse,lat=~lat, lng=~lng, popup=popup_LU, group = "Land Use Sites") %>% 
  addMarkers(data=Hospitals,lat=~LATITUDE, lng=~LONGITUDE, popup=popup_hos, group = "Hospitals",icon = makeIcon("Hos.png", "Hos-16@2x.png", 16, 16)) %>%
  addMarkers(data=USNuPowerPlant,lat=~Latitude, lng=~Longitude, popup=popup_nu, group = "Nuclear",icon = makeIcon("Nuclear.png", "Nuclear-16@2x.png", 16, 16)) %>%
  
  # Layers control
  addLayersControl(
    baseGroups = c("Cancer Rate/100,000 by Counties","Breast Cancer Rate/100,000 by Counties"),
    overlayGroups = c("Land Use Sites","Hospitals",'Nuclear'),
    options = layersControlOptions(collapsed = FALSE)
  ) 

saveWidget(gmap, 'HW10.html', selfcontained = TRUE)
```

